// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5J_SfTcPvHwrFvDuHYHd6bCQ8PnPy4bc',
    appId: '1:57286565428:web:155482215de41af9c0f461',
    messagingSenderId: '57286565428',
    projectId: 'fooddelivery-a9c47',
    authDomain: 'fooddelivery-a9c47.firebaseapp.com',
    storageBucket: 'fooddelivery-a9c47.firebasestorage.app',
    measurementId: 'G-VG60KH52W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1pyey7aNixPcCpv7JUmDGGGQDF4_7Xh0',
    appId: '1:57286565428:android:78f2e7313910719bc0f461',
    messagingSenderId: '57286565428',
    projectId: 'fooddelivery-a9c47',
    storageBucket: 'fooddelivery-a9c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBorUOvuioNbgiMAYI_AJ8IVFpjpAJs8ls',
    appId: '1:57286565428:ios:4e91fc31610678dcc0f461',
    messagingSenderId: '57286565428',
    projectId: 'fooddelivery-a9c47',
    storageBucket: 'fooddelivery-a9c47.firebasestorage.app',
    iosBundleId: 'com.example.civicfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBorUOvuioNbgiMAYI_AJ8IVFpjpAJs8ls',
    appId: '1:57286565428:ios:4e91fc31610678dcc0f461',
    messagingSenderId: '57286565428',
    projectId: 'fooddelivery-a9c47',
    storageBucket: 'fooddelivery-a9c47.firebasestorage.app',
    iosBundleId: 'com.example.civicfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5J_SfTcPvHwrFvDuHYHd6bCQ8PnPy4bc',
    appId: '1:57286565428:web:a0102817b1e0130cc0f461',
    messagingSenderId: '57286565428',
    projectId: 'fooddelivery-a9c47',
    authDomain: 'fooddelivery-a9c47.firebaseapp.com',
    storageBucket: 'fooddelivery-a9c47.firebasestorage.app',
    measurementId: 'G-H2DFPTKEZH',
  );

}